name: lsd
version: git
summary: A ls command with a lot of pretty colors.
description: lsd is a ls command including pretty icons based on nerd-font.

license: Apache-2.0
architectures:
  - amd64
  - i386
grade: stable
confinement: strict

parts:
  lsd:
    plugin: rust
    source: ./

apps:
  lsd:
    command: bin/lsd
