[package]
authors = ["Peltoche <dev@halium.fr>"]
name = "lsd"
version = "0.1.0"

[dependencies]
ansi_term = "0.11.0"
clap = "2.32.0"
lazy_static = "1.2.0"
size = "0.1.1"
time = "0.1.40"
users = "0.8.0"
