[package]
authors = ["Peltoche <dev@halium.fr>"]
categories = ["command-line-utilities"]
description = "A ls command with a lot of pretty colors."
homepage = "https://github.com/Peltoche/lsd"
keywords = ["ls"]
license-file = "./LICENSE"
name = "lsd"
readme = "./README.md"
repository = "https://github.com/Peltoche/lsd"
version = "0.1.0"

[dependencies]
ansi_term = "0.11.0"
clap = "2.32.0"
failure = "0.1.3"
lazy_static = "1.2.0"
size = "0.1.1"
terminal_size = "0.1.8"
time = "0.1.40"
users = "0.8.0"
